apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/sujitshekhar/stacks
    targetRevision: main
    repoURL: https://github.com/sujitshekhar/stacks
    targetRevision: main
    repoURL: cnoe://argo-workflows/manifests
    targetRevision: HEAD
    path: ref-implementation/ref-implementation/"dev"
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argo
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
