apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backstage
  namespace: argocd
  labels:
    env: dev
spec:
  project: default
  source:
    repoURL: https://github.com/sujitshekhar/stacks
    targetRevision: main
    path: ref-implementation/backstage/manifests
  destination:
    server: "https://kubernetes.default.svc"
    namespace: backstage
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
