apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
  labels:
    env: dev
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: external-secrets
    server: "https://kubernetes.default.svc"
  source:
    repoURL: https://github.com/sujitshekhar/stacks
    targetRevision: main
    repoURL: https://github.com/sujitshekhar/stacks
    targetRevision: main
    repoURL: cnoe://external-secrets/manifests
    targetRevision: HEAD
    path: ref-implementation/ref-implementation/"."
  project: default
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
